Implementation of the basics
educationwarehouse/persona pull request #2
Opened 2021-02-03 14:44 UTC by kevinkosterr

Changelogs:
- roles can now be created, edited and deleted
- dossiers can now be created, edited and deleted
- employment contracts can now be created, edited and deleted
- roles can't overlap
- all pages are only accessible to admin users

2021-02-08 21:10 UTC, remcoboerma requested changes
Thanks a bunch, here are my remarks and issues :)

2021-02-08 21:10 UTC, remcoboerma commented on models/db_persona.py
> +            values = [value]
Yep, that bites at times, but handled well.

2021-02-08 21:10 UTC, remcoboerma commented on models/db_persona.py
> +            role = db.rol[role_id]
This means a roundtrip to the databse for every rol used. 
Since you already have `self.roles` (which shouldn't exist, but it does at the moment) it would be better to filter that list instead. Saving the multiple roundtrips if multiple rows are selected.

2021-02-08 21:10 UTC, remcoboerma commented on models/db_persona.py
> +                pass
why?

2021-02-08 21:10 UTC, remcoboerma commented on models/db_persona.py
> +        #         return value, None
This shouldn't be in the PR right?

2021-02-08 21:10 UTC, remcoboerma commented on models/db_persona.py
> +            raise
Again, i think `__call__ =  validate` would suffice. Your `try except`ing with nothing more then a raise. so that's useless.

2021-02-08 21:10 UTC, remcoboerma commented on models/db_persona.py
> +                # were to insert a value in any other way than by a form, the inserted value still has to be unique.
Good find. well done.

2021-02-08 21:10 UTC, remcoboerma commented on models/db_persona.py
> +                                                                              IS_CAPITALIZED(),
Why should this be uppercased? 
If you would do this for case insensitivity, it's best to force a specific case. Now you force a user to work with everything UPPERCASE.

2021-02-08 21:10 UTC, remcoboerma commented on models/db_persona.py
> +                Field('rol_id', 'list:reference rol', requires=NO_ROLE_OVERLAP(), label='Rol(len)'),
Again, i really like this idea but feel that `onvalidation` is a better approach in this situation.

2021-02-09 08:32 UTC, kevinkosterr commented on models/db_persona.py
> +                Field('rol_id', 'list:reference rol', requires=NO_ROLE_OVERLAP(), label='Rol(len)'),
i'll look into `onvalidation`

2021-02-09 08:33 UTC, kevinkosterr commented on models/db_persona.py
> +                                                                              IS_CAPITALIZED(),
what do you mean? `IS_CAPITALIZED()` really forces only the first letter to be uppercase.

2021-02-09 09:45 UTC, kevinkosterr commented on models/db.py
> +auth.settings.create_user_groups = False
It wasn't indeed. I forgot that web2py automatically creates user groups for each new user, that's why I didn't mention it in the technical design document. I turned it off since we don't want a new group for each new user that is being created.

2021-02-09 09:49 UTC, kevinkosterr commented on controllers/default.py
> +    dossier = db.dossier[dossier_id]
I could also just use `db(db.dossier.id == dossier_id).select().first()`

2021-02-09 10:57 UTC, educationwarehouse commented on controllers/default.py
> +    dossier = db.dossier[dossier_id]
In which case dossier will be None, which isn't handled elsewehere

2021-02-09 14:37 UTC, educationwarehouse requested changes
Some notes while you are in progress

2021-02-09 14:37 UTC, educationwarehouse commented on models/db_functions.py
> +    """Gets the currently active 'dienstverband' records assigned to a dossier.
preference would be english i guess ;)

2021-02-09 14:37 UTC, educationwarehouse commented on models/db_persona.py
> +                                                                              IS_CAPITALIZED(),
It's not so much as what it does, but what you might expect from the naming. anything starting with `IS_` as a validator, makes the user think it will fail with an error message, but this is more like a converter, so use prefixes like `MAKE_`, `FORCE_`, or `CONVERT_` ...

2021-02-09 14:56 UTC, educationwarehouse commented on models/db.py
> +auth.settings.create_user_groups = False
Please move this into a separate PR

2021-02-09 14:58 UTC, educationwarehouse commented on controllers/default.py
> +    dossier = db.dossier[dossier_id]
outdated

2021-02-09 15:02 UTC, kevinkosterr commented on controllers/default.py
> +    return dict(dossier=dossier, form=form, dienstverbanden=dienstverbanden)
tested!

2021-02-09 15:02 UTC, kevinkosterr commented on models/db_functions.py
> +        begin = datetime.datetime.strptime(begin_date, '%Y-%m-%d')
begin_date is now a date object

2021-02-16 08:58 UTC, kevinkosterr commented on models/db_functions.py
> +    dossier in the given period of time.
dossier = person

2021-02-16 10:06 UTC, remcoboerma requested changes

2021-02-16 13:13 UTC, kevinkosterr commented on models/db_persona.py
> +                )
I'll move this to a separate PR

2021-02-16 16:25 UTC, kevinkosterr commented on models/db_functions.py
> +        form.errors.begin_date = T('This membership overlaps with another membership')
how about `'New membership period overlaps with the currently active membership period'` ?

2021-02-16 20:06 UTC, remcoboerma commented on models/db_functions.py
> +        form.errors.begin_date = T('This membership overlaps with another membership')
Informing the user is one, providing a solution is better. Tell them what to do next. Maybe add something like "if you want to split the period, change the end date and start a new period with the new set of role memberships."

2021-02-18 11:06 UTC, remcoboerma approved these changes

2021-02-18 11:06 UTC, remcoboerma commented on views/default/person.html
> +        <div class="col-sm-10"><h1>{{=person.first_name}} {{=person.last_name}}'s dossier</h1></div>
This doesn't work with German or French or maybe Turkish. We'll mark it for another D6 assignment because it works for now.

2021-02-18 11:07 UTC, merged